### ISSUE TITLE
Dependency Conflict Between ssh2-parse-key and jsonschema Regarding attrs Version

### ISSUE THREAD

**Issue by ccalero** [nigelm/ssh2_parse_key#1]
* SSH2 Key Parsing version: 0.7.2
* Python version: 3.10
* Operating System: Ubuntu

### Description

Hello,
I'm currently working on a Python project where I need to use both `ssh2-parse-key` (version 0.7.2) and `jsonschema` (version 4.21.1). However, I've encountered a dependency conflict related to the `attrs` library required by both packages.

- `ssh2-parse-key 0.7.2` depends on `attrs<21.0.0,>=20.2.0`
- `jsonschema 4.21.1` depends on `attrs>=22.2.0`

This conflict makes it impossible to satisfy the requirements of both packages simultaneously. I've explored several potential solutions, such as installing different versions of the conflicting packages or creating separate virtual environments, but these approaches are not ideal for my project's needs.
I'm reaching out to see if there's a possibility to update the package dependencies to allow for compatibility between `ssh2-parse-key` and `jsonschema`, or if there's another recommended approach to resolve this issue.

Thank you for your time and assistance.

**Comment by nigelm** [comment]
I've relaxed the dependancy specs that poetry tends to apply and pushed out a new version
